name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Update npm
        shell: bash
        run: npm install -g npm@latest

      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: Publish package
        shell: bash
        run: pnpm publish --no-git-checks